language: node_js
branches:
  only:
    - master
before_script:
  - yarn global add gatsby
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
script:
  - yarn deploy